[client]
# Hides the "Manage App" button and developer options
toolbarMode = "viewer"

# Hides the full stack trace (code) when an error occurs
showErrorDetails = false

[server]
# Ensures the app runs without trying to pop open a browser window on the server
headless = true
